### ISSUE TITLE
0.40.2 Error: Cannot find module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'

### ISSUE THREAD

**Issue by snowyu** [DavidAnson/vscode-markdownlint#158]
The [docs-linting](https://github.com/microsoft/vscode-docs-authoring/tree/main/packages/docs-linting) plugin insert the settings:

```js
  "markdownlint.customRules": [
    "{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js"
  ],
```
The Error output:

```bash
ERROR: Exception while linting:
Error: Cannot find module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'
Require stack:
- ~/.vscode/extensions/davidanson.vscode-markdownlint-0.40.2/bundle.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1019:15)
	at Function.v.resolve (/usr/share/code/resources/app/out/vs/loader.js:4:756)
	at e.exports (~/.vscode/extensions/davidanson.vscode-markdownlint-0.40.2/bundle.js:27:107212)
	at w (~/.vscode/extensions/davidanson.vscode-markdownlint-0.40.2/bundle.js:31:844)
	at ~/.vscode/extensions/davidanson.vscode-markdownlint-0.40.2/bundle.js:31:881
	at Array.map (<anonymous>)
	at E (~/.vscode/extensions/davidanson.vscode-markdownlint-0.40.2/bundle.js:31:873)
	at T (~/.vscode/extensions/davidanson.vscode-markdownlint-0.40.2/bundle.js:31:2429)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async L (~/.vscode/extensions/davidanson.vscode-markdownlint-0.40.2/bundle.js:31:5474)
```

0.40.1 works well.

**Comment by DavidAnson** [comment]
This is a deliberate feature removal - it's covered by the 3rd bullet point here: https://github.com/DavidAnson/vscode-markdownlint/blob/main/CHANGELOG.md#about-release-0400

However, I didn't realize this feature was being used widely (or at all). I don't think this is a big deal to support in the new model and will have a look soon.

**Comment by mcollier** [comment]
I'm still noticing this error with 0.42.1.  Oddly, I no longer have the **docs-linting** extension installed (uninstalled in an attempt to remove this error).

Is there a cache or something that I need to clear in Visual Studio Code?

**My VS Code info**
Version: 1.58.0-insider (user setup)
Commit: b79d23d3568db6c926c5ac428457c31f4dfc1c00
Date: 2021-06-15T15:27:03.967Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043


```shell
ERROR: Exception while linting:
Error: Cannot find module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'
Require stack:
- /home/vscode/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.42.1/bundle.js
- /vscode/vscode-server-insiders/bin/x64/b79d23d3568db6c926c5ac428457c31f4dfc1c00-insider/out/vs/loader.js
- /vscode/vscode-server-insiders/bin/x64/b79d23d3568db6c926c5ac428457c31f4dfc1c00-insider/out/bootstrap-amd.js
- /vscode/vscode-server-insiders/bin/x64/b79d23d3568db6c926c5ac428457c31f4dfc1c00-insider/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
	at Function.resolve (internal/modules/cjs/helpers.js:94:19)
	at e.exports (/home/vscode/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.42.1/bundle.js:33:4955)
	at w (/home/vscode/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.42.1/bundle.js:37:850)
	at /home/vscode/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.42.1/bundle.js:37:887
	at Array.map (<anonymous>)
	at E (/home/vscode/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.42.1/bundle.js:37:879)
	at T (/home/vscode/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.42.1/bundle.js:37:2467)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async L (/home/vscode/.vscode-server-insiders/extensions/davidanson.vscode-markdownlint-0.42.1/bundle.js:37:5546)
```

**Comment by DavidAnson** [comment]
@mcollier, that extension permanently updates the user configuration to reference its embedded custom rule: https://github.com/microsoft/vscode-docs-authoring/blob/a165fa6862659d7e2cccedf60cd47de73e193b1a/packages/docs-linting/src/controllers/lint-config-controller.ts#L66

If you remove that configuration manually from your user settings, the issue should go away.

**Comment by mcollier** [comment]
That worked.  Thank you!!!

**Comment by heaths** [comment]
I don't have the `docsmsft.docs-linting` extension installed anymore, and despite removing the configuration manually it keeps coming back. The error keeps stealing focus away from the terminal as well, making it unusable. Every time a markdown file is opened, this setting gets added back despite not having the extension installed.

**Comment by DavidAnson** [comment]
The only thing I know of that adds that setting is the docsmsft extension. You might check if the change is coming from source control, a git hook, or some kind of devcontainer process? If you find what is responsible, pease share and I'll reach out to them to ask them to stop.

**Comment by heaths** [comment]
No hooks and not using a container. Perhaps another of the extensions but wasn't obvious. Just ended up adding that extension back in to silence the error. Might just remove the whole Docs pack and installed a couple individual extensions. But at least with the extension (re)installed I don't see the error anymore. They did push out some change in January '22 that might've fixed the original error.

**Comment by peteraritchie** [comment]
For others frustrated that _docsmsft.docs-linting_ does not uninstall this conflicting configuration:  Ctrl+Shift+P: **Preferences: Open Settings**, find and remove:
```json
  "markdownlint.customRules": [
    "{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js"
  ],
```
