### ISSUE TITLE
ERROR: Exception while linting with markdownlint-cli2:

### ISSUE THREAD

**Issue by 874656645** [DavidAnson/vscode-markdownlint#218]
when I open a markdown file, these error messages keep outputting, and the output dialog keeps focused.
please look into it, 3Q

markdownlint-0.45.0

ERROR: Exception while linting with markdownlint-cli2:
Error: Cannot find module 'allowed_elements'
Require stack:
- c:\Users\cui_z\.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js
- d:\Users\cui_z\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- d:\Users\cui_z\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- d:\Users\cui_z\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Function.h.resolve (d:\Users\cui_z\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:761)
	at e.exports (c:\Users\cui_z\.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:33:2805)
	at v (c:\Users\cui_z\.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:844)
	at c:\Users\cui_z\.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:881
	at Array.map (<anonymous>)
	at w (c:\Users\cui_z\.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:873)
	at C (c:\Users\cui_z\.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:2752)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async T (c:\Users\cui_z\.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:5845)

**Comment by DavidAnson** [comment]
As a guess, this sounds like something to do with configuration because I don't expect it to try to require a module named "allowed_elements", especially because that is a parameter to one of the rules. Can you please show a simple file or configuration I can use to reproduce this?

**Comment by DavidAnson** [comment]
I've annotated the bundled/minified stack from above:

```
at e.exports (c:\Users\cui_z.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:33:2805)
	https://github.com/DavidAnson/markdownlint-cli2/blob/f697e72a53668b47e7c26a9664ce3921d058640e/resolve-and-require.js#L16

at v (c:\Users\cui_z.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:844)
	https://github.com/DavidAnson/markdownlint-cli2/blob/f697e72a53668b47e7c26a9664ce3921d058640e/markdownlint-cli2.js#L60

at c:\Users\cui_z.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:881
	https://github.com/DavidAnson/markdownlint-cli2/blob/f697e72a53668b47e7c26a9664ce3921d058640e/markdownlint-cli2.js#L67

at Array.map ()

at w (c:\Users\cui_z.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:873)
	https://github.com/DavidAnson/markdownlint-cli2/blob/f697e72a53668b47e7c26a9664ce3921d058640e/markdownlint-cli2.js#L67

at C (c:\Users\cui_z.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:2752)
	https://github.com/DavidAnson/markdownlint-cli2/blob/f697e72a53668b47e7c26a9664ce3921d058640e/markdownlint-cli2.js#L399

at runMicrotasks ()

at processTicksAndRejections (internal/process/task_queues.js:93:5)

at async T (c:\Users\cui_z.vscode\extensions\davidanson.vscode-markdownlint-0.45.0\bundle.js:37:5845)
	https://github.com/DavidAnson/markdownlint-cli2/blob/f697e72a53668b47e7c26a9664ce3921d058640e/markdownlint-cli2.js#L681
```

The important part is here: https://github.com/DavidAnson/markdownlint-cli2/blob/f697e72a53668b47e7c26a9664ce3921d058640e/markdownlint-cli2.js#L399

That shows the extension processing the "customRules" property from one of your project's configuration files trying to `require` each of the strings in the array. Per the exception text, it appears that one of those strings is `allowed_elements` and we can infer that package is not present in `node_modules`.

That is not a valid package name: https://www.npmjs.com/search?q=allowed_elements

But it is a valid property for rule MD033: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033

So this looks like an issue with the configuration of your project as I guessed above.

**Comment by 874656645** [comment]
I guess so. Maybe I changed settings before. But I forget how to open the config file. I did not find .vs folder under my project folder either. I reinstalled VS Code, but the error is still there. How can I change the settings back?

**Comment by 874656645** [comment]
Thank you for your help. The problem is done. I find where the setting file is. “\AppData\Roaming\Code\User\settings.json”
But, question is I can only put the file which named ".markdownlint.json" in the project directory?
Can I make the settings worked on all my markdown files in different folders?

**Comment by DavidAnson** [comment]
Glad you got this figured out! You can put configuration in VS Code user settings where it will apply to all projects that do not have their own configuration, you can put it in VS Code workspace settings where it will apply only to that workspace, or you can use a configuration file in the root of the project where it will apply only to the project. More about those options here: https://github.com/DavidAnson/vscode-markdownlint#markdownlintconfig

**Comment by 874656645** [comment]
Thank you again. I figured it out finally. I'll close this issue.
