### ISSUE TITLE
ERROR: Exception while linting with markdownlint-cli2

### ISSUE THREAD

**Issue by hichemfantar** [DavidAnson/vscode-markdownlint#264]
This error pops up whenever a .md file is opened.
```
[1:51:47 AM] ERROR: Exception while linting with markdownlint-cli2:
Error: Cannot find module '{docsmsft.docs-linting}/markdownlint-custom-rules/rules.js'
Require stack:
- c:\Users\user\.vscode\extensions\davidanson.vscode-markdownlint-0.48.1\bundle.js
- c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js / Invalid host defined options
	at w (c:\Users\user\.vscode\extensions\davidanson.vscode-markdownlint-0.48.1\bundle.js:37:6800)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
	at async Promise.all (index 0)
	at async T (c:\Users\user\.vscode\extensions\davidanson.vscode-markdownlint-0.48.1\bundle.js:37:9515)
	at async L (c:\Users\user\.vscode\extensions\davidanson.vscode-markdownlint-0.48.1\bundle.js:37:13852)

```

**Comment by nschonni** [comment]
That's caused by https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack. Unfortunatly they turned off the issue tracker for that repo. I think the fix is to edit your VSCode preferences, because they auto-inject some settings there

**Comment by DavidAnson** [comment]
See the last few comments of #158 for how to fix this.
