### ISSUE TITLE
0.49.0 -  / Invalid host defined options

### ISSUE THREAD

**Issue by agardnerIT** [DavidAnson/vscode-markdownlint#282]
markdownlint is the only extension I have installed.

```
[20:11:48] ERROR: Exception while linting with markdownlint-cli2:
Error: Cannot find module 'markdownlint-rule-max-one-sentence-per-line'
Require stack:
- /Users/.../.vscode/extensions/davidanson.vscode-markdownlint-0.49.0/bundle.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
-  / Invalid host defined options
	at x (/Users/.../.vscode/extensions/davidanson.vscode-markdownlint-0.49.0/bundle.js:37:6800)
	at async Promise.all (index 0)
	at async Promise.all (index 0)
	at async T (/Users/.../.vscode/extensions/davidanson.vscode-markdownlint-0.49.0/bundle.js:37:9515)
	at async L (/Users/.../.vscode/extensions/davidanson.vscode-markdownlint-0.49.0/bundle.js:37:13839)
```

**Comment by DavidAnson** [comment]
The project you are linting has been configured to use the custom rule "markdownlint-rule-max-one-sentence-per-line", but that rule could not be loaded. You should be able to find the relevant configuration file and remove the reference to this rule or install that rule within the project and reference it there. Note that this configuration may be coming from user or workspace settings in VS Code.
